### ISSUE TITLE
Calendar re-selects deselected date

### ISSUE THREAD

**Issue by ttajic** [iyegoroff/kendo-multi-calendar#2]
To replicate the bug:
- select multiple dates in a month, then deselect a date you have last selected
- go to next/previous month and then return to the original month
- the last date (you have deselected) is selected again

You can try it on a demo here:
https://kendo-multi-calendar.surge.sh/

**Comment by ttajic** [comment]
I think I fixed it by adding  i._value = null; when de-delecting a date ...

you do it in typescript :)

e.prototype.updateSelection = function (t, n) {
            var i = this;
            if (void 0 === t && (t = []), void 0 === n && (n = []), this._index === e._views[this.options.depth]) {
                t.forEach(function (t) {
                    i.cellByDate(i.view().toDateString(t)).addClass("k-state-selected")
                }), n.forEach(function (t) {
                    **i._value = null;**
                    i.cellByDate(i.view().toDateString(t)).removeClass("k-state-selected")
                })
            }
        }

**Comment by iyegoroff** [comment]
Hi @ttajic, thanks for feedback! This is fixed now in v2.2.6.
